import type { RouteCoverageRow } from "./types";

export const seedRoutes: RouteCoverageRow[] = [
  {
    "ruta_id": "S0001",
    "fuente_hoja": "SEED",
    "estado": "CDMX",
    "ruta": "BENITO JUÁREZ",
    "poblacion": "DEL VALLE CENTRO",
    "codigo_postal": "03100",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0002",
    "fuente_hoja": "SEED",
    "estado": "CDMX",
    "ruta": "CUAUHTÉMOC",
    "poblacion": "ROMA NORTE",
    "codigo_postal": "06700",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0003",
    "fuente_hoja": "SEED",
    "estado": "EDO MEX",
    "ruta": "NAUCALPAN DE JUÁREZ",
    "poblacion": "SATÉLITE",
    "codigo_postal": "53100",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0004",
    "fuente_hoja": "SEED",
    "estado": "EDO MEX",
    "ruta": "TLALNEPANTLA DE BAZ",
    "poblacion": "CENTRO",
    "codigo_postal": "54000",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0005",
    "fuente_hoja": "SEED",
    "estado": "TOLUCA",
    "ruta": "TOLUCA",
    "poblacion": "CENTRO",
    "codigo_postal": "50000",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0006",
    "fuente_hoja": "SEED",
    "estado": "TOLUCA",
    "ruta": "METEPEC",
    "poblacion": "SAN JERÓNIMO CHICAHUALCO",
    "codigo_postal": "52170",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0007",
    "fuente_hoja": "SEED",
    "estado": "PUEBLA",
    "ruta": "PUEBLA",
    "poblacion": "CENTRO",
    "codigo_postal": "72000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": false,
    "miercoles": true,
    "jueves": false,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0008",
    "fuente_hoja": "SEED",
    "estado": "PUEBLA",
    "ruta": "SAN PEDRO CHOLULA",
    "poblacion": "CENTRO",
    "codigo_postal": "72760",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": false,
    "martes": true,
    "miercoles": false,
    "jueves": true,
    "viernes": false,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0009",
    "fuente_hoja": "SEED",
    "estado": "QUERÉTARO",
    "ruta": "SANTIAGO DE QUERÉTARO",
    "poblacion": "CENTRO",
    "codigo_postal": "76000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": false,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0010",
    "fuente_hoja": "SEED",
    "estado": "MORELOS",
    "ruta": "CUERNAVACA",
    "poblacion": "CENTRO",
    "codigo_postal": "62000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": false,
    "miercoles": true,
    "jueves": false,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0011",
    "fuente_hoja": "SEED",
    "estado": "TLAXCALA",
    "ruta": "TLAXCALA",
    "poblacion": "CENTRO",
    "codigo_postal": "90000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": false,
    "martes": true,
    "miercoles": false,
    "jueves": true,
    "viernes": false,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0012",
    "fuente_hoja": "SEED",
    "estado": "VERACRUZ",
    "ruta": "XALAPA",
    "poblacion": "CENTRO",
    "codigo_postal": "91000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": false,
    "miercoles": true,
    "jueves": false,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0013",
    "fuente_hoja": "SEED",
    "estado": "MICHOACÁN",
    "ruta": "MORELIA",
    "poblacion": "CENTRO",
    "codigo_postal": "58000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": false,
    "martes": true,
    "miercoles": false,
    "jueves": true,
    "viernes": false,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0014",
    "fuente_hoja": "SEED",
    "estado": "GUERRERO",
    "ruta": "CHILPANCINGO",
    "poblacion": "CENTRO",
    "codigo_postal": "39000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": false,
    "miercoles": false,
    "jueves": true,
    "viernes": false,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0015",
    "fuente_hoja": "SEED",
    "estado": "OAXACA",
    "ruta": "OAXACA DE JUÁREZ",
    "poblacion": "CENTRO",
    "codigo_postal": "68000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": false,
    "requiere_asesor": true,
    "lunes": false,
    "martes": false,
    "miercoles": false,
    "jueves": false,
    "viernes": false,
    "sabado": false,
    "mensaje_opcional": "Ruta de prueba marcada para asesor desde Excel/admin; no hardcodear por estado.",
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0016",
    "fuente_hoja": "SEED",
    "estado": "JALISCO",
    "ruta": "GUADALAJARA",
    "poblacion": "CENTRO",
    "codigo_postal": "44100",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": false,
    "cotizacion_automatica": false,
    "requiere_asesor": true,
    "lunes": false,
    "martes": false,
    "miercoles": false,
    "jueves": false,
    "viernes": false,
    "sabado": false,
    "mensaje_opcional": "Ruta desactivada para probar fallback de asesor.",
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0017",
    "fuente_hoja": "SEED",
    "estado": "NUEVO LEÓN",
    "ruta": "MONTERREY",
    "poblacion": "CENTRO",
    "codigo_postal": "64000",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": false,
    "requiere_asesor": true,
    "lunes": false,
    "martes": false,
    "miercoles": false,
    "jueves": false,
    "viernes": false,
    "sabado": false,
    "mensaje_opcional": "Ruta activa pero no cotizable automáticamente; requiere asesor.",
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0018",
    "fuente_hoja": "SEED",
    "estado": "CDMX",
    "ruta": "MIGUEL HIDALGO",
    "poblacion": "POLANCO",
    "codigo_postal": "11560",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0019",
    "fuente_hoja": "SEED",
    "estado": "EDO MEX",
    "ruta": "ECATEPEC DE MORELOS",
    "poblacion": "CENTRO",
    "codigo_postal": "55000",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0020",
    "fuente_hoja": "SEED",
    "estado": "QUERÉTARO",
    "ruta": "EL MARQUÉS",
    "poblacion": "ZIBATÁ",
    "codigo_postal": "76269",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": false,
    "martes": true,
    "miercoles": false,
    "jueves": true,
    "viernes": false,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0021",
    "fuente_hoja": "SEED",
    "estado": "PUEBLA",
    "ruta": "CUAUTLANCINGO",
    "poblacion": "CENTRO",
    "codigo_postal": "72700",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": false,
    "requiere_asesor": true,
    "lunes": false,
    "martes": false,
    "miercoles": true,
    "jueves": false,
    "viernes": false,
    "sabado": false,
    "mensaje_opcional": "Ruta activa pero cotización automática desactivada; debe mandar a asesor.",
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0022",
    "fuente_hoja": "SEED",
    "estado": "CDMX",
    "ruta": "COYOACÁN",
    "poblacion": "DEL CARMEN",
    "codigo_postal": "04100",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0023",
    "fuente_hoja": "SEED",
    "estado": "EDO MEX",
    "ruta": "HUIXQUILUCAN",
    "poblacion": "INTERLOMAS",
    "codigo_postal": "52787",
    "zona_operativa": "Área Metropolitana",
    "tipo_tarifa": "Local",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": true,
    "miercoles": true,
    "jueves": true,
    "viernes": true,
    "sabado": true,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  },
  {
    "ruta_id": "S0024",
    "fuente_hoja": "SEED",
    "estado": "MORELOS",
    "ruta": "JIUTEPEC",
    "poblacion": "CENTRO",
    "codigo_postal": "62550",
    "zona_operativa": "Foráneo",
    "tipo_tarifa": "Foránea",
    "activo": true,
    "cotizacion_automatica": true,
    "requiere_asesor": false,
    "lunes": true,
    "martes": false,
    "miercoles": true,
    "jueves": false,
    "viernes": true,
    "sabado": false,
    "mensaje_opcional": null,
    "version_cobertura": "seed-v1",
    "fecha_actualizacion": "2026-05-01"
  }
];

export function findRouteByPostalCode(originCp: string, destinationCp: string): RouteCoverageRow | undefined {
  // Seed simplification:
  // For the first implementation, use destination CP to determine coverage and tariff behavior.
  // Later this should be replaced by a full origin-destination route resolver from admin data.
  return seedRoutes.find((route) => route.codigo_postal === destinationCp);
}

// Place lookup by CP — used for origin detection (display only, no route validity check)
export function findPlaceByPostalCode(cp: string): RouteCoverageRow | undefined {
  return seedRoutes.find((route) => route.codigo_postal === cp)
}

export function routeRequiresAdvisor(route: RouteCoverageRow | undefined): boolean {
  if (!route) return true;
  return !route.activo || !route.cotizacion_automatica || route.requiere_asesor;
}
